spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # For MySQL 8.x use "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
