spring:  
  datasource:
    url: jdbc:mysql://${commons.mysql.host.name}:${commons.mysql.host.port}/${commons.mysql.db_name}
    username: ${commons.mysql.username}
    password: ${commons.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver # For MySQL 8.x use "com.mysql.cj.jdbc.Driver"
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka-server/
