server:
  port: 8072
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoint:
    gateway:
      enabled: true